site_name: ILLIXR Docs
theme: ivory
nav:
    - Home: 'index.md'
    - 'Core':
        - 'Spindle': 'core/spindle.md'
        - 'Phonebook': 'core/phonebook.md'
    - 'Components':  
        - 'OpenVINS': 'components/open_vins.md'
        - 'Offline IMU and Camera': 'components/offline_imu_cam.md'
