plugin_groups:
  - !include "rt_slam_plugins.yaml"
  - !include "core_plugins.yaml"
  - plugin_group:
    - path: ground_truth_slam/
    - path: gldemo/

data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/

enable_offload:   False
enable_alignment: False
enable_verbose_errors: False

action:
  name: tests
  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO/
profile: dbg
