plugin_group:
  - path: timewarp_gl/
  # - name: audio
  #   path:
  #     git_repo: https://github.com/ILLIXR/audio_pipeline.git
  #     version: 3433bb452b2ec661c9d3ef65d9cf3a2805e94cdc
  # - name: hologram
  #   path:
  #     git_repo: https://github.com/ILLIXR/HOTlab.git
  #     version: 51b8ef86cb1efa1204cb4a33dfaf15bb09d66903
