plugin_group:
  - path: timewarp_gl/
  - name: audio
    path:
      git_repo: https://github.com/ILLIXR/audio_pipeline.git
      version: "2.0"
  # - name: hologram
  #   path:
  #     git_repo: https://github.com/ILLIXR/HOTlab.git
  #     version: "2.0"
