---
### Global definitions visible to all modules ###
# 
# Users are free to place any new (arbitrary) constant definitions here
# Definitions can take the form of a key value pair where the value is either a:
#
#  A. String containing the value to be destringified at run-time
#     _or_
#  B. Simple or complex path as defined by `$ref: "#/definitions/path"`,
#     as long the key name ends in "_PATH"
#
# Example definitions of values of type 'A'
#
#    FB_WIDTH:     "2560"  # Pixels (int)
#    FB_HEIGHT:    "1400"  # Pixels (int)
#    RUN_DURATION: "60"    # Seconds (long)
#    REFRESH_RATE: "60.0"  # Hz (double)
#
# For examples of type 'B', see the globally included data paths below
#
#################################################

# URI to offline IMU/cam data (omit if not applicable)
DATA_PATH:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'

# URI to objects to render in gldemo
DEMO_OBJ_PATH: demo_data/
---
