plugin_groups:
  - !include "rt_slam_plugins.yaml"
  - plugin_group:
      - path: ground_truth_slam/
      - path: gldemo/
  - !include "core_plugins.yaml"

enable_offload:   False
enable_alignment: False
enable_verbose_errors: False
enable_pre_sleep: False

action:
  name: native
  command: xvfb-run $cmd
  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/
  audio_path:  .cache/paths/https%c%s%sgithub.com%sILLIXR%saudio_pipeline.git/
profile: opt

constants:
  - !include "global_module_defs.yaml"
