plugin_groups:
  - !include "rt_slam_plugins.yaml"
  - !include "core_plugins.yaml"

data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/

enable_offload:   False
enable_alignment: False
enable_verbose_errors: False

action:
  name: monado
  monado:
    path:
      git_repo: https://github.com/ILLIXR/monado_integration.git
      version: master
  openxr_app:
    path:
      git_repo: https://github.com/ILLIXR/Monado_OpenXR_Simple_Example.git
      version: master
    config: {}
profile: opt
