plugin_groups:
  - !include "rt_slam_plugins.yaml"
  - !include "core_plugins.yaml"

data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/

enable_offload        : False
enable_alignment      : False
enable_verbose_errors : False
enable_pre_sleep      : False
# realsense_cam         : auto

action:
  name        : monado

  monado:
    path:
      git_repo : https://github.com/ILLIXR/monado_integration.git
      version  : "add-timewarp-semaphore" # Note: this should be changed to master when the corresponding branch is merged

    config: # For CMake
      XRT_HAVE_LIBUDEV              : ON
      XRT_HAVE_LIBUSB               : ON
      XRT_HAVE_LIBUVC               : ON
      XRT_HAVE_V4L2                 : ON
      XRT_HAVE_SDL2                 : OFF
      XRT_BUILD_DRIVER_ANDROID      : OFF
      XRT_BUILD_DRIVER_ARDUINO      : OFF
      XRT_BUILD_DRIVER_DAYDREAM     : OFF
      XRT_BUILD_DRIVER_DEPTHAI      : OFF
      XRT_BUILD_DRIVER_EUROC        : OFF
      XRT_BUILD_DRIVER_HANDTRACKING : OFF
      XRT_BUILD_DRIVER_HDK          : OFF
      XRT_BUILD_DRIVER_HYDRA        : OFF
      XRT_BUILD_DRIVER_NS           : OFF
      XRT_BUILD_DRIVER_OHMD         : OFF
      XRT_BUILD_DRIVER_OPENGLOVES   : OFF
      XRT_BUILD_DRIVER_PSMV         : OFF
      XRT_BUILD_DRIVER_PSVR         : OFF
      XRT_BUILD_DRIVER_QWERTY       : OFF
      XRT_BUILD_DRIVER_REALSENSE    : OFF
      XRT_BUILD_DRIVER_REMOTE       : OFF
      XRT_BUILD_DRIVER_RIFT_S       : OFF
      XRT_BUILD_DRIVER_SURVIVE      : OFF
      XRT_BUILD_DRIVER_ULV2         : OFF
      XRT_BUILD_DRIVER_VF           : OFF
      XRT_BUILD_DRIVER_VIVE         : OFF
      XRT_BUILD_DRIVER_HANDTRACKING : OFF
      XRT_BUILD_DRIVER_WMR          : OFF
      XRT_BUILD_DRIVER_SIMULAVR     : OFF
      XRT_BUILD_DRIVER_SIMULATED    : OFF
      XRT_BUILD_SAMPLES             : OFF
      XRT_FEATURE_TRACING           : OFF
      XRT_FEATURE_SERVICE           : ON
      XRT_FEATURE_WINDOW_PEEK       : OFF


  openxr_apps: 
    - !include "openxr_app.yaml"

  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/
  audio_path:  .cache/paths/https%c%s%sgithub.com%sILLIXR%saudio_pipeline.git/

  # command: gdb -q --args $cmd

profile: opt
