plugin_groups:
  - plugin_group:
    - path: offline_imu_cam
    - path: gtsam_integrator
    - path: pose_prediction
    - name: OpenVINS
      path:
        git_repo : https://github.com/ILLIXR/open_vins.git
        version  : "3.0"

data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/

enable_offload        : False
enable_alignment      : False
enable_verbose_errors : False
enable_pre_sleep      : False
# realsense_cam         : auto

action:
  name: monado
  is_mainline: True

  monado:
    path:
      git_repo : https://gitlab.freedesktop.org/monado/monado.git
      version  : main

    config: # For CMake
      XRT_HAVE_LIBUDEV              : ON
      XRT_HAVE_LIBUSB               : ON
      XRT_HAVE_LIBUVC               : ON
      XRT_HAVE_V4L2                 : ON
      XRT_HAVE_SDL2                 : ON
      XRT_BUILD_DRIVER_ARDUINO      : OFF
      XRT_BUILD_DRIVER_OHMD         : OFF
      XRT_BUILD_DRIVER_DAYDREAM     : OFF
      XRT_BUILD_DRIVER_DUMMY        : OFF
      XRT_BUILD_DRIVER_HDK          : OFF
      XRT_BUILD_DRIVER_HYDRA        : OFF
      XRT_BUILD_DRIVER_NS           : OFF
      XRT_BUILD_DRIVER_PSMV         : OFF
      XRT_BUILD_DRIVER_PSVR         : OFF
      XRT_BUILD_DRIVER_RS           : OFF
      XRT_BUILD_DRIVER_REMOTE       : OFF
      XRT_BUILD_DRIVER_SURVIVE      : OFF
      XRT_BUILD_DRIVER_VIVE         : OFF
      XRT_BUILD_DRIVER_HANDTRACKING : OFF
      XRT_BUILD_DRIVER_WMR          : OFF
      XRT_FEATURE_SERVICE           : ON

  openxr_app: !include "openxr_app.yaml"

  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/
  audio_path:  .cache/paths/https%c%s%sgithub.com%sILLIXR%saudio_pipeline.git/

profile: opt
