plugin_groups:
  - !include "rt_slam_plugins.yaml"
  - plugin_group:
      - path: gldemo/
      # - path: debugview/
  - !include "core_plugins.yaml"

data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/
loader:
  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO/
  name: native
  # command: gdb -q --args %a
  # command: valgrind %a
profile: opt
