plugin_groups:
  - !include "rt_slam_plugins.yaml"
  - plugin_group:
      - path: ground_truth_slam/
      - path: gldemo/
      - path: debugview/
      - path: offload_data/
  - !include "core_plugins.yaml"

enable_offload:   False
enable_alignment: False
enable_verbose_errors: False
enable_pre_sleep: False
# realsense_cam: auto

action:
  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/
  audio_path:  .cache/paths/https%c%s%sgithub.com%sILLIXR%saudio_pipeline.git/
  name: native

  # run in GDB:
  # command: gdb -q --args $cmd

  # Print cmd for external use:
  # command: printf %s\n $env_cmd

  # Capture stdout for metrics
  # log_stdout: metrics/output.log

profile: opt

constants:
  - !include "global_module_defs.yaml"
