##
## Configuration to run integrated ILLIXR natively with pose lookup
##

action:
  name: native

  kimera_path: !include "data/kimera-default.yaml"
  audio_path:  !include "data/audio-default.yaml"

  # run in GDB:
  # command: gdb -q --args $cmd

  # Print cmd for external use:
  # command: printf %s\n $env_cmd

  # Capture stdout for metrics
  # log_stdout: metrics/output.log

common:    !include "plugins/common.yaml"
runtime:   !include "plugins/runtime.yaml"
data:      !include "data/data-default.yaml"
demo_data: !include "data/demo-default.yaml"

profile: opt

flows:
  - !include "ci/flows/lookup.yaml"
append: !include "plugins/groups/misc-native.yaml"
