plugin_groups:
  - plugin_group:
      - path: offline_imu/
      - path: offline_cam/
      # - path: zed/
      # - path: rk4_integrator/
      - path: gtsam_integrator/
      # - path: passthrough_integrator/
      - path: pose_prediction/
      # - path: ground_truth_slam/
      # - path: gldemo/
      # - path: debugview/
      # - path: offload_data/
      # - path: record_imu_cam/
      - path: offload_vio/device_rx/
      - path: offload_vio/device_tx/
  - !include "core_plugins.yaml"

data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/

enable_offload        : False
enable_alignment      : False
enable_verbose_errors : False
enable_pre_sleep      : False
# enable_slogging        : True
# realsense_cam         : auto

action:
  name        : monado
  is_mainline : False

  monado:
    path: ../monado_integration
      # git_repo : https://github.com/ILLIXR/monado_integration.git
      # version  : "offload-vio"

    config: # For CMake
      BUILD_WITH_LIBUDEV : "0"
      BUILD_WITH_LIBUSB  : "0"
      BUILD_WITH_LIBUVC  : "0"
      BUILD_WITH_NS      : "0"
      BUILD_WITH_PSMV    : "0"
      BUILD_WITH_PSVR    : "0"
      BUILD_WITH_OPENHMD : "0"
      BUILD_WITH_VIVE    : "0"

  openxr_app: !include "openxr_app.yaml"

  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/
  audio_path:  .cache/paths/https%c%s%sgithub.com%sILLIXR%saudio_pipeline.git/

  # command: gdb -q --args $cmd
  # log_stdout: metrics/output.log
  ILLIXR_RUN_DURATION: 200

profile: opt
