# NOTE: If running OpenVINS with the ZED mini, download the repo using Option 1, then modify
# .cache/paths/https%c%s%sgithub.com%sILLIXR%sopen_vins.git/ov_msckf/src/slam2.cpp 
# and uncomment line 23 (the ZED define). After this modification you will need to use Option 2 instead of 1.

plugin_groups:
  - plugin_group:
      - path: offload_vio/server_rx/
      - path: offload_vio/server_tx/

      #################################################################
      ### ONLY ONE OF THE FOLLOWING SHOULD BE UNCOMMENTED AT A TIME ###
      #################################################################

      # Option 1: Uncomment if OpenVINS hasnt been fetched from remote (Default).
      - name: OpenVINS
        path:
           git_repo: https://github.com/ILLIXR/open_vins.git
           version: "issue-50-separate-imu-cam"

      # Option 2: Uncomment if you made changes to OpenVINS and want those to be reflected in the subsequent ILLIXR runs.
      # - path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sopen_vins.git/

      # Option 3: Uncomment if Kimera hasnt been fetched from remote.
      # - name: Kimera-VIO/
      #   path:
      #     git_repo: https://github.com/ILLIXR/Kimera-VIO.git
      #     version: "3.2"

      # Option 4: Uncomment if you made changes to Kimera and want those to be reflected in the subsequent ILLIXR runs.
      # - path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/

      #################################################################

data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/

enable_offload:   False
enable_alignment: False
enable_verbose_errors: False
enable_pre_sleep: False
# realsense_cam: auto

action:
  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/
  audio_path:  .cache/paths/https%c%s%sgithub.com%sILLIXR%saudio_pipeline.git/
  name: native

  # run in GDB:
  # command: gdb -q --args $cmd

  # Print cmd for external use:
  # command: printf %s\n $env_cmd

  # Capture stdout for metrics
  # log_stdout: metrics/output.log

profile: opt
