plugin_group:
  - path: offline_imu_cam/
  # - path: zed/
  # - name: Kimera-VIO/
  #   path:
  #     git_repo: https://github.com/ILLIXR/Kimera-VIO
  #     version: 6ea99d33fc2435a8c514049416dcb2f8a0e31692
  # - name: OpenVINS
  #   path:
  #     git_repo: https://github.com/ILLIXR/open_vins.git
  #     version: 065a964087622126ed4c1911aeb18d253b034208
  - path: ../ILLIXR_comp/open_vins
  - path: gtsam_integrator/
  - path: pose_prediction/
  # - path: pose_lookup/
