plugin_group:
  - path: offline_imu_cam/
  # - path: zed/
  # - path: realsense/
  # - path: depthai/
  - name: Kimera-VIO/
    path:
      git_repo: https://github.com/ILLIXR/Kimera-VIO.git
      version: "3.1"
  # - name: OpenVINS
  #   path:
  #      git_repo: https://github.com/ILLIXR/open_vins.git
  #      version: "3.0"
  # - path: rk4_integrator/
  - path: gtsam_integrator/
  - path: pose_prediction/
