plugin_group:
  - path: offline_imu/
  - path: offline_cam/
  # - path: zed/
  # - path: realsense/
  # - path: depthai/
  # - path: record_imu_cam/
  - name: Kimera-VIO/
    path:
      git_repo: https://github.com/ILLIXR/Kimera-VIO.git
      version: "3.2"
  # - name: OpenVINS
  #   path:
  #     git_repo: https://github.com/ILLIXR/open_vins.git
  #     version: "issue-58-standardize-clock"
  # - path: rk4_integrator/
  - path: gtsam_integrator/
  - path: pose_prediction/
