name: illixr-runner
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - attrs=20.1.0=py_0
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py38_0
  - click=7.1.2=py_0
  - importlib-metadata=1.7.0=py38_0
  - importlib_metadata=1.7.0=0
  - jsonschema=3.2.0=py38_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1g=h7b6447c_0
  - pip=20.2.2=py38_0
  - pyrsistent=0.16.0=py38h7b6447c_0
  - python=3.8.5=hcff3b4d_0
  - pyyaml=5.3.1=py38h7b6447c_1
  - readline=8.0=h7b6447c_0
  - setuptools=49.6.0=py38_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - pyyaml-include==1.2

