name: illixr-tests-master

on:
  push:
    branches: [ master ]

jobs:
  illixr-tests-master:
    runs-on: ubuntu-18.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Login to ghcr.io
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u illixr-ci --password-stdin

      - name: Extract Master Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      # Pulls latest and current branch tag of this container. This allows the docker build to use the cache for faster builds. 
      - name: Pull Docker Cache
        run: docker pull ghcr.io/illixr/illixr-tests:${{ steps.extract_branch.outputs.branch }} || docker pull ghcr.io/illixr/illixr-tests:latest|| true

      # Performs the docker build and pulls the cache from either the branch name tag or from latest.
      # The latest tag is what is on master so it will use that cache the first time this branch runs
      - name: Build Docker Image
        run: docker build --build-arg JOBS="$(nproc)" --cache-from ghcr.io/illixr/illixr-tests:${{ steps.extract_branch.outputs.branch }},ghcr.io/illixr/illixr-tests:latest . -t ghcr.io/illixr/illixr-tests:${{ steps.extract_branch.outputs.branch }}

      - name: Push Docker Image
        run: docker push ghcr.io/illixr/illixr-tests:${{ steps.extract_branch.outputs.branch }}

      # For builds on master we also want to push the image as the latest tag.
      - if: steps.extract_branch.outputs.branch == 'master'
        name: Tag Master Docker Image As Latest
        run: docker tag ghcr.io/illixr/illixr-tests:${{ steps.extract_branch.outputs.branch }} ghcr.io/illixr/illixr-tests:latest && docker push ghcr.io/illixr/illixr-tests:latest

      - name: Pull Docker Image
        run: docker pull ghcr.io/illixr/illixr-tests:${{ steps.extract_branch.outputs.branch }}

      - name: Run Tests
        run: docker run ghcr.io/illixr/illixr-tests:${{ steps.extract_branch.outputs.branch }}
